site_name: BGCA · 1r de Batxillerat
site_description: Materials guia de Biologia, Geologia i Ciències Ambientals

theme:
  name: material
  language: ca

nav:
  - Inici: index.md
  - "UD 1 · Com reconstruïm la història de la Terra?": ud01/ud01.md
  - "UD 2 · Una Terra dinàmica": ud02/ud02.md

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
